server:
  port: 8081

spring:
  mail:
    host: smtp.mailtrap.io
    port: 465
    username: 5badbb71d135e3
    password: b902bdc5400589
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/drive
    username: glaze
    password: straightdalmatian
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

drive:
  base:
    folder: /home/glaze/Projects/tinyDrive/Drive/

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: metrics, health, info, beans

application:
  jwt:
    configuration:
      prefix: Bearer 
      validity-in-days: 5
      secret-key: SuperHyperSecretKeyImpossibleToGuessByAnyLivingCretureInThisWholeUniverseMultiverseOrWhateverDimensionExist